name: lab-datawarehouse
services:
  webspoon:
    build: .
    ports:
      - 8880:8080
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8881:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pg@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Pa55w0rd
    volumes:
      - ./pgadmin:/var/lib/pgadmin